DELETE  http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZjY4ZTgzMjU4YmViMDE4NjVkMjBlYSIsImlhdCI6MTY5Mzk4NDg0MSwiZXhwIjoxNjkzOTg4NDQxfQ.Si-9FeaN71-XenVtT-_5QQ-WYwYQ2e57td7GNibAut0